baseURL = ""
title = "David Pantoja"
author = "David Pantoja"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "hugo-casper3"

[params]
  facebook = "https://www.instagram.com/david.pant_/"
  twitter = "https://twitter.com"
  github = "https://github.com/jonathanjanssens"
  description = "A site all about me!"
  mainSections = ["post"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "image-credit"
    name = "Image Credit"
    url = "/image-credit/"
    weight = 20
  [[menu.main]]
    identifier = "github-repo-theme"
    name = "Contact info"
    url = "/contactinfo/"
    weight = 30
  [[menu.main]]
    identifier = "author"
    name = "Timeline"
    url = "/timeline/"
    weight = 40

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true